import {readFileSync,writeFileSync} from 'node:fs';
const data=JSON.parse(readFileSync(new URL('../data/world-roads.json',import.meta.url),'utf8'));
const lines=[...data.lines,...data.seams];
const quote=s=>JSON.stringify(s);
const junctions=new Set([...data.lines.flatMap(l=>l.points),...data.externalJunctions].map(p=>p.join(',')));
for(const seam of data.seams){
  if(seam.points.some(p=>!junctions.has(p.join(','))))throw Error(`Unconnected zone handoff: ${seam.name}`);
}
for(const line of lines){
  if(!['Both','Alliance','Horde'].includes(line.faction)||!['road','corridor','transition'].includes(line.kind))throw Error(line.name);
  if(line.points.length<2||line.points.some(p=>p.length!==3||p.some(v=>!Number.isFinite(v))||p[0]<1||p.slice(1).some(v=>v<0||v>100)))throw Error(line.name);
}
const out=['local _,F=...', '-- Generated by tools/build-roads.mjs; edit data/world-roads.json.',
  '-- Reviewed map art, not collision or live enemy data. See data limitations.',
  'local lines=F.roadData.lines',
  'local function add(name,faction,kind,points) lines[#lines+1]={name=name,faction=faction,kind=kind,points=points} end'];
for(const l of lines)out.push(`add(${quote(l.name)},${quote(l.faction)},${quote(l.kind)},{${l.points.map(p=>`{${p.join(',')}}`).join(',')}})`);
out.push(`F.roadData.coverage={${data.maps.map(m=>m.id).join(',')}}`);
out.push('F.roadData.cityFactions={[1453]="Alliance",[1455]="Alliance",[1457]="Alliance",[1454]="Horde",[1456]="Horde",[1458]="Horde"}');
writeFileSync(new URL('../WaylaidForever/WorldRoadData.lua',import.meta.url),out.join('\n')+'\n');
console.log(`${lines.length} regional paths/handoffs; ${data.maps.length} reviewed maps`);
