import { readFile, writeFile, rename, stat } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

export const MARKETS = ['pvp','normal','rp'].flatMap(type => ['horde','alliance'].map(f => `forever.${type}.${f}.us`));
export function parseTable(raw, market, now = Math.floor(Date.now()/1000)) {
  if (!MARKETS.includes(market)) throw new Error('Unsupported market');
  const lines = raw.trim().split(/\r?\n/);
  const [version, scope, timestamp, count] = lines.shift().split('|');
  const time = Number(timestamp);
  if (version !== 'AHL1' || scope !== market.replaceAll('.', '/') ||
      !/^\d+$/.test(timestamp) || !Number.isSafeInteger(time) || time <= 0 || time > now + 300 ||
      !/^\d+$/.test(count) || Number(count) !== lines.length) throw new Error('Invalid or incomplete AHledger table');
  const items = {};
  for (const line of lines) {
    const [id, median, minimum, quantity] = line.split(':');
    if (!/^\d+$/.test(id) || !Number.isSafeInteger(Number(id)) || Number(id) <= 0 ||
        [median,minimum,quantity].some(v => v != null && v !== '' && (!/^\d+$/.test(v) || !Number.isSafeInteger(Number(v))))) {
      throw new Error('Invalid AHledger row');
    }
    if (Number(minimum) > 0) items[id] = [Number(minimum), quantity === '' || quantity == null ? null : Number(quantity)];
  }
  return {time,items};
}
export function renderLua(feeds) {
  const rows = ['-- AHledger.com snapshot. Generated by tools/sync-prices.mjs.', 'local _, F = ...', 'F.bundledPrices = {'];
  for (const market of MARKETS) {
    const feed = feeds[market];
    if (!feed) continue;
    if (!Number.isSafeInteger(feed.time) || feed.time <= 0) throw new Error('Invalid cached timestamp');
    rows.push(`["${market}"]={time=${feed.time},items={`);
    for (const [id,[price,qty]] of Object.entries(feed.items).sort((a,b)=>Number(a[0])-Number(b[0]))) {
      if (!/^\d+$/.test(id) || !Number.isSafeInteger(Number(id)) || Number(id) <= 0 ||
          !Number.isSafeInteger(price) || price <= 0 || (qty != null && (!Number.isSafeInteger(qty) || qty < 0))) throw new Error('Invalid cached price');
      rows.push(`[${id}]={${price},${qty ?? 'nil'}},`);
    }
    rows.push('}},');
  }
  return rows.join('\n') + '\n}\n';
}
export async function sync({ directory, markets = MARKETS, now = Math.floor(Date.now()/1000), fetcher = fetch }) {
  if (!markets.length || markets.some(m => !MARKETS.includes(m))) throw new Error('Unsupported market');
  await stat(join(directory, 'ForeverWaylaid.toc'));
  const cacheFile = join(directory,'.ahledger-cache.json');
  let cache = {feeds:{},next:{}};
  try { cache = JSON.parse(await readFile(cacheFile,'utf8')); } catch(e) { if(e.code !== 'ENOENT') throw e; }
  const errors = [], messages = [];
  for (const market of markets) {
    if ((cache.next[market] || 0) > now) { messages.push(`${market}: cached until ${new Date(cache.next[market]*1000).toISOString()}`); continue; }
    try {
      const response = await fetcher('https://api.ahledger.com/v1/pricetable/' + market, {signal:AbortSignal.timeout(30000)});
      if (!response.ok) throw new Error(`AHledger returned ${response.status}`);
      const raw = await response.text();
      if (raw.length > 8_000_000) throw new Error('AHledger table exceeds size limit');
      const feed = parseTable(raw,market,now);
      if (!cache.feeds[market] || feed.time >= cache.feeds[market].time) cache.feeds[market] = feed;
      const serverAge = Number(response.headers.get('cache-control')?.match(/(?:^|[,\s])max-age=(\d+)/)?.[1] || 0);
      cache.next[market] = now + Math.max(1800,serverAge);
      messages.push(`${market}: ${Object.keys(feed.items).length} prices, observed ${new Date(feed.time*1000).toISOString()}`);
    } catch(e) { errors.push(`${market}: ${e.message}; previous snapshot retained`); }
  }
  if (!Object.keys(cache.feeds).length) throw new Error(errors.join('\n') || 'No AHledger data available');
  const lua = renderLua(cache.feeds);
  // A failed download never replaces a good market; a partial file is never loaded.
  await writeFile(join(directory,'Prices.lua.tmp'),lua);
  await rename(join(directory,'Prices.lua.tmp'),join(directory,'Prices.lua'));
  await writeFile(cacheFile+'.tmp',JSON.stringify(cache));
  await rename(cacheFile+'.tmp',cacheFile);
  return {messages,errors};
}
async function main() {
  const args = process.argv.slice(2);
  if (args.includes('--help')) {
    console.log('node tools/sync-prices.mjs [--addon-dir PATH/ForeverWaylaid] [--market forever.pvp.horde.us] [--watch]'); return;
  }
  let directory = fileURLToPath(new URL('../ForeverWaylaid/',import.meta.url)), markets = MARKETS, watch = false;
  for (let i=0;i<args.length;i++) {
    if (args[i] === '--addon-dir' && args[i+1]) directory = resolve(args[++i]);
    else if (args[i] === '--market' && args[i+1]) markets = [args[++i]];
    else if (args[i] === '--watch') watch = true;
    else throw new Error('Unknown or incomplete option: ' + args[i]);
  }
  do {
    const result = await sync({directory,markets});
    result.messages.forEach(m=>console.log(m)); result.errors.forEach(e=>console.error(e));
    console.log('In WoW, /reload to load the snapshot. Prices: https://ahledger.com/');
    if (!watch) { if(result.errors.length) process.exitCode=1; break; }
    await new Promise(r=>setTimeout(r,1800000));
  } while(watch);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main().catch(e=>{console.error(e.message);process.exitCode=1;});
